spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zlp123
    url: jdbc:mysql://localhost:3306/zStar?serverTimezone=UTC&characterEncoding=utf8&useSSL=false&useUnicode=true
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB


mybatis:
  mapper-locations: classpath*:com/zlp/blog/blog_api/dao/mapper/*.xml
  type-aliases-package: com.zlp.blog.blog_api.dao.pojo
  configuration:
   # log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

qiniu:
  accessKey: H3rpPUoJC-n8h8NRcay4klTrBRZzh9Q_2-uE11qc
  secretKey: KWlPJAo4keO1EFkeH5FryrKdply4ZO5px7AnuyhS





